//
//  PredefinedFruitsFoods.swift
//  Calorie Hunter
//
//  Auto-generated on request
//

import Foundation

struct PredefinedFruitsFoods {
    static let foods: [FoodItem] = [
        // MARK: - Citrus Fruits
                FoodItem(name: "Orange", calories: 47, protein: 0.9, carbs: 12, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Navel Orange", calories: 49, protein: 0.9, carbs: 12.5, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Blood Orange", calories: 45, protein: 0.9, carbs: 11.8, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Seville Orange", calories: 45, protein: 0.8, carbs: 11, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mandarin", calories: 53, protein: 0.8, carbs: 13, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Tangerine", calories: 53, protein: 0.8, carbs: 13, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Clementine", calories: 47, protein: 0.9, carbs: 12, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Satsuma", calories: 42, protein: 0.6, carbs: 10.5, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Kinnow", calories: 50, protein: 0.8, carbs: 11.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Dekopon", calories: 46, protein: 0.9, carbs: 12, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Tangor", calories: 52, protein: 0.8, carbs: 13, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Tangelo", calories: 50, protein: 0.8, carbs: 13, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Lemon", calories: 29, protein: 1.1, carbs: 9.3, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Meyer Lemon", calories: 29, protein: 1, carbs: 8.2, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Lime", calories: 30, protein: 0.7, carbs: 10.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Key Lime", calories: 30, protein: 0.7, carbs: 10.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Kaffir Lime", calories: 30, protein: 0.5, carbs: 7.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Desert Lime", calories: 27, protein: 1, carbs: 7.6, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sweet Lime (Mosambi)", calories: 43, protein: 0.7, carbs: 11, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Grapefruit", calories: 42, protein: 0.8, carbs: 11, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "White Grapefruit", calories: 39, protein: 0.8, carbs: 10.6, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Red Grapefruit", calories: 43, protein: 0.9, carbs: 11.2, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Pomelo", calories: 38, protein: 0.8, carbs: 9.6, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Oroblanco", calories: 40, protein: 0.6, carbs: 10.5, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Yuzu", calories: 20, protein: 0.8, carbs: 7, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sudachi", calories: 20, protein: 0.8, carbs: 6.5, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Kabosu", calories: 22, protein: 0.9, carbs: 7.1, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Shonan Gold", calories: 48, protein: 0.8, carbs: 12.1, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Etrog", calories: 30, protein: 0.7, carbs: 9.2, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Citron", calories: 25, protein: 0.6, carbs: 9.1, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Calamansi", calories: 37, protein: 0.8, carbs: 9.1, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Bergamot Orange", calories: 36, protein: 0.6, carbs: 8.5, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Ugli Fruit", calories: 47, protein: 0.9, carbs: 11, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Ichang Papeda", calories: 27, protein: 0.9, carbs: 7.2, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Micrantha", calories: 29, protein: 0.7, carbs: 8.9, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Djeruk limo", calories: 28, protein: 0.8, carbs: 8.4, fat: 0.2, grams: 100, mealType: "Snack"),
        // MARK: - Berries
                FoodItem(name: "Strawberry", calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Blueberry", calories: 57, protein: 0.7, carbs: 14, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Raspberry", calories: 52, protein: 1.2, carbs: 12, fat: 0.7, grams: 100, mealType: "Snack"),
                FoodItem(name: "Blackberry", calories: 43, protein: 1.4, carbs: 10, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cranberry", calories: 46, protein: 0.4, carbs: 12.2, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Goji Berry", calories: 349, protein: 14.3, carbs: 77, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Acai Berry", calories: 70, protein: 1.4, carbs: 4, fat: 5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Bilberry", calories: 57, protein: 0.7, carbs: 14.5, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cloudberry", calories: 51, protein: 0.8, carbs: 12.4, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Elderberry", calories: 73, protein: 0.7, carbs: 18.4, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mulberry", calories: 43, protein: 1.4, carbs: 9.8, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Boysenberry", calories: 50, protein: 1.4, carbs: 13, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Huckleberry", calories: 37, protein: 0.4, carbs: 9.3, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Juneberry", calories: 82, protein: 0.9, carbs: 19, fat: 0.7, grams: 100, mealType: "Snack"),
                FoodItem(name: "Serviceberry", calories: 81, protein: 1, carbs: 18.9, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Lingonberry", calories: 48, protein: 0.7, carbs: 11, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Salmonberry", calories: 45, protein: 0.9, carbs: 10, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Thimbleberry", calories: 47, protein: 1.2, carbs: 11.5, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Wineberry", calories: 49, protein: 1.1, carbs: 12.3, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Chokeberry (Aronia)", calories: 47, protein: 1.4, carbs: 9.6, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Maqui Berry", calories: 55, protein: 1.2, carbs: 14, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Barberry", calories: 316, protein: 3.6, carbs: 63.9, fat: 3.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Gooseberry", calories: 44, protein: 1, carbs: 10, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Redcurrant", calories: 56, protein: 1.4, carbs: 13.8, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Blackcurrant", calories: 63, protein: 1.4, carbs: 15.4, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Whitecurrant", calories: 57, protein: 1.3, carbs: 13, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cape Gooseberry", calories: 53, protein: 1.9, carbs: 11.2, fat: 0.7, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sea Buckthorn", calories: 82, protein: 1.2, carbs: 14.9, fat: 5.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Bearberry", calories: 40, protein: 0.6, carbs: 11, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Oregon Grape", calories: 55, protein: 1, carbs: 13.2, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Snowberry", calories: 36, protein: 0.5, carbs: 10.1, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Farkleberry", calories: 42, protein: 0.8, carbs: 11, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Dangleberry", calories: 45, protein: 0.9, carbs: 12.4, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Coralberry", calories: 38, protein: 0.6, carbs: 9.7, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Crowberry", calories: 52, protein: 0.7, carbs: 12, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Dewberry", calories: 43, protein: 1.1, carbs: 10.5, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Bayberry", calories: 48, protein: 0.9, carbs: 12.6, fat: 0.2, grams: 100, mealType: "Snack"),
        // MARK: - Tropical Fruits
                FoodItem(name: "Mango", calories: 60, protein: 0.8, carbs: 15, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Papaya", calories: 43, protein: 0.5, carbs: 11, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Guava", calories: 68, protein: 2.6, carbs: 14, fat: 1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Pineapple", calories: 50, protein: 0.5, carbs: 13, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Banana", calories: 89, protein: 1.1, carbs: 23, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Avocado", calories: 160, protein: 2, carbs: 9, fat: 15, grams: 100, mealType: "Snack"),
                FoodItem(name: "Durian", calories: 147, protein: 1.5, carbs: 27, fat: 5.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Jackfruit", calories: 95, protein: 1.7, carbs: 23, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Soursop", calories: 66, protein: 1, carbs: 16.8, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sapodilla", calories: 83, protein: 0.4, carbs: 20, fat: 1.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Rambutan", calories: 68, protein: 0.9, carbs: 17, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mangosteen", calories: 73, protein: 0.4, carbs: 18, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Pulasan", calories: 82, protein: 0.9, carbs: 21, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Langsat", calories: 57, protein: 0.8, carbs: 14, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Salak", calories: 82, protein: 0.8, carbs: 22.3, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Atemoya", calories: 94, protein: 1.3, carbs: 23.6, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cherimoya", calories: 75, protein: 1.6, carbs: 18.1, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Lucuma", calories: 100, protein: 1.4, carbs: 25, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cupuacu", calories: 65, protein: 1, carbs: 10, fat: 4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Baobab", calories: 250, protein: 2, carbs: 45, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Passion Fruit", calories: 97, protein: 2.2, carbs: 23, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Carambola", calories: 31, protein: 1, carbs: 6.7, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Breadfruit", calories: 103, protein: 1.1, carbs: 27.1, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Tamarind", calories: 239, protein: 2.8, carbs: 63.8, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Dragon Fruit", calories: 50, protein: 1.1, carbs: 13, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Longan", calories: 60, protein: 1, carbs: 15, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Lychee", calories: 66, protein: 0.8, carbs: 17, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Ackee", calories: 151, protein: 2.9, carbs: 2.9, fat: 15.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Marang", calories: 102, protein: 1.3, carbs: 27, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Camu Camu", calories: 17, protein: 0.4, carbs: 4, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Feijoa", calories: 55, protein: 0.6, carbs: 13, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Santol", calories: 88, protein: 0.6, carbs: 22, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Ambarella", calories: 67, protein: 0.5, carbs: 16.7, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Jaboticaba", calories: 58, protein: 0.6, carbs: 15.3, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "White Sapote", calories: 80, protein: 1.3, carbs: 20, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Spanish Lime", calories: 58, protein: 0.8, carbs: 14.3, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Nance", calories: 82, protein: 1.5, carbs: 18, fat: 1.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Persimmon", calories: 70, protein: 0.6, carbs: 18, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Loquat", calories: 47, protein: 0.4, carbs: 12, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Bael Fruit", calories: 137, protein: 1.8, carbs: 31, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cactus Pear", calories: 41, protein: 0.7, carbs: 10, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Barbadine", calories: 75, protein: 0.5, carbs: 18, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Velvet Apple", calories: 60, protein: 0.9, carbs: 14.5, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Yangmei", calories: 28, protein: 0.8, carbs: 7.2, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mountain Soursop", calories: 63, protein: 1, carbs: 15, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Oil Palm Fruit", calories: 500, protein: 1.6, carbs: 6, fat: 53, grams: 100, mealType: "Snack"),
                FoodItem(name: "Rose Apple", calories: 25, protein: 0.6, carbs: 5.7, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Soncoya", calories: 91, protein: 2.3, carbs: 22, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Custard Apple", calories: 94, protein: 2.1, carbs: 23.6, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Malay Apple", calories: 32, protein: 0.6, carbs: 7.6, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Desert Lime", calories: 27, protein: 1, carbs: 7.6, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Indian Fig", calories: 41, protein: 0.8, carbs: 10.2, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Chayote", calories: 19, protein: 0.8, carbs: 4.5, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Brazil Nut Fruit", calories: 656, protein: 14.3, carbs: 12.3, fat: 66.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Akee Apple", calories: 151, protein: 2.9, carbs: 2.9, fat: 15.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Lansium", calories: 57, protein: 1.2, carbs: 14.2, fat: 0.2, grams: 100, mealType: "Snack"),
        // MARK: - Temperate Fruits
                FoodItem(name: "Apple", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Pear", calories: 57, protein: 0.4, carbs: 15, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Quince", calories: 57, protein: 0.4, carbs: 15.3, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Grape (Red)", calories: 69, protein: 0.7, carbs: 18.1, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Grape (Green)", calories: 67, protein: 0.6, carbs: 17.2, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cherry", calories: 50, protein: 1, carbs: 12, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Plum", calories: 46, protein: 0.7, carbs: 11.4, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Apricot", calories: 48, protein: 1.4, carbs: 11, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Peach", calories: 39, protein: 0.9, carbs: 10, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Nectarine", calories: 44, protein: 1.1, carbs: 10.6, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Gooseberry", calories: 44, protein: 1, carbs: 10, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Currant (Red)", calories: 56, protein: 1.4, carbs: 13.8, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Currant (Black)", calories: 63, protein: 1.4, carbs: 15.4, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "White Currant", calories: 57, protein: 1.3, carbs: 13, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mulberry", calories: 43, protein: 1.4, carbs: 9.8, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Medlar", calories: 47, protein: 0.4, carbs: 12, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Serviceberry", calories: 81, protein: 1, carbs: 18.9, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Juneberry", calories: 82, protein: 0.9, carbs: 19, fat: 0.7, grams: 100, mealType: "Snack"),
                FoodItem(name: "Rowanberry", calories: 47, protein: 0.5, carbs: 11.4, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Hawthorn Berry", calories: 50, protein: 1.2, carbs: 13, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Barberry", calories: 316, protein: 3.6, carbs: 63.9, fat: 3.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sloe (Blackthorn)", calories: 45, protein: 1, carbs: 11, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Elderberry", calories: 73, protein: 0.7, carbs: 18.4, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cornelian Cherry", calories: 58, protein: 0.6, carbs: 15.5, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Crabapple", calories: 50, protein: 0.4, carbs: 13, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mountain Ash Berry", calories: 49, protein: 0.7, carbs: 12.1, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Japanese Persimmon", calories: 70, protein: 0.6, carbs: 18, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Damson", calories: 46, protein: 0.7, carbs: 11.4, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Loquat", calories: 47, protein: 0.4, carbs: 12, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Greengage", calories: 46, protein: 0.6, carbs: 10.2, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mirabelle Plum", calories: 52, protein: 0.7, carbs: 12.4, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Italian Prune Plum", calories: 51, protein: 0.7, carbs: 13, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Wild Apple (Malus sieversii)", calories: 50, protein: 0.3, carbs: 13.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Asian Pear", calories: 42, protein: 0.5, carbs: 11.3, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Boysenberry", calories: 50, protein: 1.4, carbs: 13, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Huckleberry", calories: 37, protein: 0.4, carbs: 9.3, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Lingonberry", calories: 48, protein: 0.7, carbs: 11, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Beach Plum", calories: 45, protein: 0.6, carbs: 10.1, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Winter Banana Apple", calories: 55, protein: 0.3, carbs: 14.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Black Raspberry", calories: 52, protein: 1.5, carbs: 11.9, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Loganberry", calories: 47, protein: 1.2, carbs: 12.3, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "American Persimmon", calories: 81, protein: 0.8, carbs: 21, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Chequers (Service Tree fruit)", calories: 65, protein: 0.9, carbs: 16, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Whitebeam Berry", calories: 50, protein: 0.7, carbs: 13.2, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Autumn Olive (Elaeagnus umbellata)", calories: 49, protein: 0.8, carbs: 11.5, fat: 0.2, grams: 100, mealType: "Snack"),
        // MARK: - Stone Fruits (Drupes)
                FoodItem(name: "Peach", calories: 39, protein: 0.9, carbs: 10, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Nectarine", calories: 44, protein: 1.1, carbs: 10.6, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Apricot", calories: 48, protein: 1.4, carbs: 11, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Plum", calories: 46, protein: 0.7, carbs: 11.4, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cherry", calories: 50, protein: 1, carbs: 12, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Black Cherry", calories: 63, protein: 1.2, carbs: 16, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sour Cherry", calories: 50, protein: 1.6, carbs: 12.2, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Rainier Cherry", calories: 60, protein: 1.1, carbs: 15, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Damson Plum", calories: 46, protein: 0.7, carbs: 11.4, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Greengage", calories: 42, protein: 0.8, carbs: 10.2, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mirabelle Plum", calories: 52, protein: 0.7, carbs: 12.3, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Yellow Plum", calories: 47, protein: 0.6, carbs: 11, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Italian Prune Plum", calories: 55, protein: 0.8, carbs: 13, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mume (Japanese Apricot)", calories: 45, protein: 0.9, carbs: 10.8, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Jocote", calories: 85, protein: 0.9, carbs: 22, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mamoncillo (Spanish Lime)", calories: 58, protein: 0.8, carbs: 14.3, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Olive (ripe)", calories: 115, protein: 0.8, carbs: 6.3, fat: 10.7, grams: 100, mealType: "Snack"),
                FoodItem(name: "Olive (green)", calories: 145, protein: 1, carbs: 3.8, fat: 15.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Date Plum (Diospyros lotus)", calories: 66, protein: 0.8, carbs: 17.6, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Indian Jujube (Ber)", calories: 79, protein: 1.2, carbs: 20.2, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Wild Peach", calories: 45, protein: 0.7, carbs: 10.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Desert Date (Balanites aegyptiaca)", calories: 135, protein: 2.1, carbs: 30, fat: 2.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Chinese Date (Ziziphus jujuba)", calories: 79, protein: 1.2, carbs: 20.2, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Canistel (Egg Fruit)", calories: 140, protein: 1.5, carbs: 36.7, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Lucuma (also a drupe)", calories: 100, protein: 1.4, carbs: 25, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Spondias mombin (Yellow Mombin)", calories: 80, protein: 0.9, carbs: 19.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Spondias purpurea (Red Mombin)", calories: 85, protein: 1, carbs: 21, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "African Wild Mango (Dika)", calories: 120, protein: 2.5, carbs: 20, fat: 6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Bitter Almond (unprocessed)", calories: 575, protein: 21, carbs: 22, fat: 49, grams: 100, mealType: "Snack"),
                FoodItem(name: "Chokecherry", calories: 60, protein: 0.8, carbs: 14, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Beach Plum", calories: 52, protein: 0.6, carbs: 12.4, fat: 0.2, grams: 100, mealType: "Snack"),
        // MARK: - Melons
                FoodItem(name: "Watermelon", calories: 30, protein: 0.6, carbs: 8, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cantaloupe", calories: 34, protein: 0.8, carbs: 8, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Honeydew", calories: 36, protein: 0.5, carbs: 9, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Galia Melon", calories: 34, protein: 0.8, carbs: 8.2, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Canary Melon", calories: 36, protein: 0.5, carbs: 9, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Santa Claus Melon", calories: 32, protein: 0.6, carbs: 7.9, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Hami Melon", calories: 36, protein: 0.6, carbs: 8.6, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Korean Melon", calories: 31, protein: 0.6, carbs: 7.2, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Winter Melon", calories: 13, protein: 0.4, carbs: 3, fat: 0, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sprite Melon", calories: 38, protein: 0.7, carbs: 9.6, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Horned Melon (Kiwano)", calories: 44, protein: 1.8, carbs: 7.6, fat: 1.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Charentais Melon", calories: 34, protein: 0.9, carbs: 7.9, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Bitter Melon", calories: 17, protein: 1, carbs: 3.7, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Snap Melon", calories: 28, protein: 0.6, carbs: 6.5, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Piel de Sapo Melon", calories: 31, protein: 0.8, carbs: 7.6, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Tiger Melon", calories: 32, protein: 0.6, carbs: 8, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Ogen Melon", calories: 34, protein: 0.8, carbs: 7.8, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Muskmelon", calories: 35, protein: 0.9, carbs: 8.2, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Crenshaw Melon", calories: 39, protein: 0.8, carbs: 9, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Golden Langkawi Melon", calories: 33, protein: 0.6, carbs: 7.7, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sweet Granite Melon", calories: 36, protein: 0.7, carbs: 8.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Ivory Gaya Melon", calories: 34, protein: 0.6, carbs: 8.1, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Armenian Cucumber (Melon)", calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Caspaba Melon", calories: 35, protein: 0.6, carbs: 8.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Banana Melon", calories: 34, protein: 0.8, carbs: 7.9, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Ha'Ogen Melon", calories: 33, protein: 0.8, carbs: 7.6, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Gaya Melon", calories: 35, protein: 0.8, carbs: 8.4, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Early Silver Line Melon", calories: 32, protein: 0.7, carbs: 8.1, fat: 0.1, grams: 100, mealType: "Snack"),
        // MARK: - Pome Fruits
                FoodItem(name: "Apple", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Pear", calories: 57, protein: 0.4, carbs: 15, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Asian Pear", calories: 42, protein: 0.6, carbs: 10.6, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Quince", calories: 57, protein: 0.4, carbs: 15.3, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Crabapple", calories: 50, protein: 0.4, carbs: 13, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Medlar", calories: 47, protein: 0.4, carbs: 12, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Loquat", calories: 47, protein: 0.4, carbs: 12, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Rowanberry", calories: 47, protein: 0.5, carbs: 11.4, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Serviceberry", calories: 81, protein: 1, carbs: 18.9, fat: 0.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Juneberry", calories: 82, protein: 0.9, carbs: 19, fat: 0.7, grams: 100, mealType: "Snack"),
                FoodItem(name: "Mountain Ash Berry", calories: 49, protein: 0.7, carbs: 12.1, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sorb Apple", calories: 50, protein: 0.8, carbs: 13.5, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Nashi Pear", calories: 42, protein: 0.5, carbs: 10.6, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Choke Pear", calories: 56, protein: 0.4, carbs: 14.1, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Tejocote (Mexican Hawthorn)", calories: 65, protein: 0.8, carbs: 17, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Snow Pear", calories: 54, protein: 0.4, carbs: 13, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Callery Pear", calories: 58, protein: 0.5, carbs: 14, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Miquel Pear", calories: 60, protein: 0.6, carbs: 15.2, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Indian Wild Apple", calories: 48, protein: 0.4, carbs: 12.7, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Toringo Crabapple", calories: 51, protein: 0.5, carbs: 13.4, fat: 0.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Yunnan Crabapple", calories: 53, protein: 0.4, carbs: 13.2, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Chinese White Pear", calories: 44, protein: 0.4, carbs: 11, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Siberian Crabapple", calories: 46, protein: 0.5, carbs: 12.8, fat: 0.2, grams: 100, mealType: "Snack"),
        // MARK: - Dry Fruits
                FoodItem(name: "Almond", calories: 579, protein: 21.2, carbs: 21.7, fat: 49.9, grams: 100, mealType: "Snack"),
                FoodItem(name: "Walnut", calories: 654, protein: 15.2, carbs: 13.7, fat: 65.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Pistachio", calories: 562, protein: 20.2, carbs: 27.5, fat: 45.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Hazelnut", calories: 628, protein: 15, carbs: 17, fat: 61, grams: 100, mealType: "Snack"),
                FoodItem(name: "Cashew", calories: 553, protein: 18.2, carbs: 30.2, fat: 43.8, grams: 100, mealType: "Snack"),
                FoodItem(name: "Pecan", calories: 691, protein: 9.2, carbs: 13.9, fat: 71.9, grams: 100, mealType: "Snack"),
                FoodItem(name: "Macadamia", calories: 718, protein: 7.9, carbs: 13.8, fat: 75.8, grams: 100, mealType: "Snack"),
                FoodItem(name: "Brazil Nut", calories: 659, protein: 14.3, carbs: 11.7, fat: 67.1, grams: 100, mealType: "Snack"),
                FoodItem(name: "Pine Nut", calories: 673, protein: 13.7, carbs: 13.1, fat: 68.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Chestnut (dried)", calories: 370, protein: 5.5, carbs: 82, fat: 3.6, grams: 100, mealType: "Snack"),
                FoodItem(name: "Tiger Nut", calories: 486, protein: 4, carbs: 47, fat: 24, grams: 100, mealType: "Snack"),
                FoodItem(name: "Coconut (dried)", calories: 660, protein: 6.9, carbs: 23.6, fat: 64.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sunflower Seed (dry)", calories: 584, protein: 20.8, carbs: 20, fat: 51.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Pumpkin Seed", calories: 559, protein: 30.2, carbs: 10.7, fat: 49, grams: 100, mealType: "Snack"),
                FoodItem(name: "Chia Seed", calories: 486, protein: 16.5, carbs: 42.1, fat: 30.7, grams: 100, mealType: "Snack"),
                FoodItem(name: "Flaxseed", calories: 534, protein: 18.3, carbs: 28.9, fat: 42.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Sesame Seed", calories: 573, protein: 17.7, carbs: 23.4, fat: 49.7, grams: 100, mealType: "Snack"),
                FoodItem(name: "Watermelon Seed (dried)", calories: 557, protein: 28.3, carbs: 15.3, fat: 47.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Lotus Seed (dried)", calories: 332, protein: 15.4, carbs: 64.5, fat: 1.9, grams: 100, mealType: "Snack"),
                FoodItem(name: "Date (dried)", calories: 277, protein: 1.8, carbs: 75, fat: 0.2, grams: 100, mealType: "Snack"),
                FoodItem(name: "Fig (dried)", calories: 249, protein: 3.3, carbs: 63.9, fat: 0.9, grams: 100, mealType: "Snack"),
                FoodItem(name: "Raisin", calories: 299, protein: 3.1, carbs: 79.2, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Prune (dried plum)", calories: 240, protein: 2.2, carbs: 63.9, fat: 0.4, grams: 100, mealType: "Snack"),
                FoodItem(name: "Apricot (dried)", calories: 241, protein: 3.4, carbs: 62.6, fat: 0.5, grams: 100, mealType: "Snack"),
                FoodItem(name: "Apple (dried)", calories: 243, protein: 0.9, carbs: 65.9, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Banana (dried)", calories: 346, protein: 3.9, carbs: 88.3, fat: 1.8, grams: 100, mealType: "Snack"),
                FoodItem(name: "Currant (dried)", calories: 283, protein: 3.1, carbs: 74.1, fat: 0.3, grams: 100, mealType: "Snack"),
                FoodItem(name: "Goji Berry (dried)", calories: 349, protein: 14.3, carbs: 77, fat: 0.4, grams: 100, mealType: "Snack")
                
    ]
}
