//
//  PredefinedMeatFoods.swift
//  Calorie Hunter
//
//  Created by Jude Mawad on 02.05.25.
//


import Foundation

struct PredefinedMeatFoods {
    static let foods: [FoodItem] = [
        // Chicken Cuts
        FoodItem(name: "Chicken Whole (Raw)", calories: 193, protein: 16.7, carbs: 0, fat: 13.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Whole (Cooked)", calories: 215, protein: 18.5, carbs: 0, fat: 15.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Skinless Breast (Raw)", calories: 148, protein: 27.9, carbs: 0, fat: 3.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Skinless Breast (Cooked)", calories: 165, protein: 31, carbs: 0, fat: 3.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Breast with Skin (Raw)", calories: 177, protein: 26.1, carbs: 0, fat: 7.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Breast with Skin (Cooked)", calories: 197, protein: 29, carbs: 0, fat: 8.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Tenderloin (Raw)", calories: 102, protein: 21.6, carbs: 0, fat: 1.7, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Tenderloin (Cooked)", calories: 114, protein: 24, carbs: 0, fat: 1.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Thigh Skinless (Raw)", calories: 188, protein: 23.4, carbs: 0, fat: 9.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Thigh Skinless (Cooked)", calories: 209, protein: 26, carbs: 0, fat: 10.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Thigh with Skin (Raw)", calories: 206, protein: 22.5, carbs: 0, fat: 12.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Thigh with Skin (Cooked)", calories: 229, protein: 25, carbs: 0, fat: 13.4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Drumstick Skinless (Raw)", calories: 145, protein: 16.2, carbs: 0, fat: 8.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Drumstick Skinless (Cooked)", calories: 162, protein: 18, carbs: 0, fat: 9.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Drumstick with Skin (Raw)", calories: 168, protein: 15.3, carbs: 0, fat: 12.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Drumstick with Skin (Cooked)", calories: 187, protein: 17, carbs: 0, fat: 13.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Wing Skinless (Raw)", calories: 182, protein: 26.1, carbs: 0, fat: 7.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Wing Skinless (Cooked)", calories: 203, protein: 29, carbs: 0, fat: 8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Wing with Skin (Raw)", calories: 217, protein: 25.2, carbs: 0, fat: 13.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Wing with Skin (Cooked)", calories: 242, protein: 28, carbs: 0, fat: 15, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Leg Quarter (Raw)", calories: 171, protein: 22.5, carbs: 0, fat: 9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Leg Quarter (Cooked)", calories: 190, protein: 25, carbs: 0, fat: 10, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Neck (Raw)", calories: 193, protein: 17.1, carbs: 0, fat: 13.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Neck (Cooked)", calories: 215, protein: 19, carbs: 0, fat: 15, grams: 100, mealType: "Protein"),

        FoodItem(name: "Chicken Back (Raw)", calories: 154, protein: 17.1, carbs: 0, fat: 9.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Back (Cooked)", calories: 172, protein: 19, carbs: 0, fat: 11, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Feet (Trotters) (Raw)", calories: 193, protein: 17.1, carbs: 0, fat: 13.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Feet (Trotters) (Cooked)", calories: 215, protein: 19, carbs: 0, fat: 15, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Skin (Raw)", calories: 494, protein: 3.9, carbs: 0, fat: 48.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Skin (Cooked)", calories: 549, protein: 4.3, carbs: 0, fat: 54, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Oyster (Raw)", calories: 166, protein: 18, carbs: 0, fat: 9.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Oyster (Cooked)", calories: 185, protein: 20, carbs: 0, fat: 11, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Liver (Raw)", calories: 107, protein: 15.3, carbs: 0.81, fat: 4.32, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Liver (Cooked)", calories: 119, protein: 17, carbs: 0.9, fat: 4.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Gizzard (Raw)", calories: 84, protein: 27, carbs: 0, fat: 1.35, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Gizzard (Cooked)", calories: 94, protein: 30, carbs: 0, fat: 1.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Fat (Schmaltz) (Raw)", calories: 808, protein: 0, carbs: 0, fat: 89.55, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Fat (Schmaltz) (Cooked)", calories: 898, protein: 0, carbs: 0, fat: 99.5, grams: 100, mealType: "Protein"),

        // Beef Cuts
        FoodItem(name: "Beef Ribeye Steak (Raw)", calories: 261, protein: 20.7, carbs: 0, fat: 18.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Ribeye Steak (Cooked)", calories: 291, protein: 23, carbs: 0, fat: 21, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Rib Steak Bone-In (Raw)", calories: 254, protein: 21.6, carbs: 0, fat: 18, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Rib Steak Bone-In (Cooked)", calories: 283, protein: 24, carbs: 0, fat: 20, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Rib Steak Boneless (Raw)", calories: 249, protein: 21.6, carbs: 0, fat: 17.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Rib Steak Boneless (Cooked)", calories: 277, protein: 24, carbs: 0, fat: 19, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Strip Steak (New York Strip) (Raw)", calories: 246, protein: 20.7, carbs: 0, fat: 18, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Strip Steak (New York Strip) (Cooked)", calories: 274, protein: 23, carbs: 0, fat: 20, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Sirloin Steak (Raw)", calories: 179, protein: 25.2, carbs: 0, fat: 7.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Sirloin Steak (Cooked)", calories: 199, protein: 28, carbs: 0, fat: 8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Tenderloin (Filet Mignon) (Raw)", calories: 192, protein: 23.4, carbs: 0, fat: 10.08, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Tenderloin (Filet Mignon) (Cooked)", calories: 214, protein: 26, carbs: 0, fat: 11.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef T-Bone Steak (Raw)", calories: 225, protein: 19.8, carbs: 0, fat: 15.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef T-Bone Steak (Cooked)", calories: 251, protein: 22, carbs: 0, fat: 17, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Porterhouse Steak (Raw)", calories: 216, protein: 21.6, carbs: 0, fat: 13.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Porterhouse Steak (Cooked)", calories: 241, protein: 24, carbs: 0, fat: 15, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Flank Steak (Raw)", calories: 172, protein: 23.4, carbs: 0, fat: 7.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Flank Steak (Cooked)", calories: 192, protein: 26, carbs: 0, fat: 8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Skirt Steak (Raw)", calories: 180, protein: 23.4, carbs: 0, fat: 9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Skirt Steak (Cooked)", calories: 200, protein: 26, carbs: 0, fat: 10, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Hanger Steak (Raw)", calories: 217, protein: 22.5, carbs: 0, fat: 13.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Hanger Steak (Cooked)", calories: 242, protein: 25, carbs: 0, fat: 15, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Tri-Tip Steak (Raw)", calories: 201, protein: 24.3, carbs: 0, fat: 10.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Tri-Tip Steak (Cooked)", calories: 224, protein: 27, carbs: 0, fat: 12, grams: 100, mealType: "Protein"),
        FoodItem(name: "Ground Beef (85% lean) (Raw)", calories: 228, protein: 15.3, carbs: 0, fat: 18, grams: 100, mealType: "Protein"),
        FoodItem(name: "Ground Beef (85% lean) (Cooked)", calories: 254, protein: 17, carbs: 0, fat: 20, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Brisket Flat Cut (Raw)", calories: 171, protein: 19.8, carbs: 0, fat: 9.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Brisket Flat Cut (Cooked)", calories: 190, protein: 22, carbs: 0, fat: 11, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Brisket Point Cut (Raw)", calories: 288, protein: 16.2, carbs: 0, fat: 24.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Brisket Point Cut (Cooked)", calories: 320, protein: 18, carbs: 0, fat: 27, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Short Ribs (Raw)", calories: 262, protein: 14.4, carbs: 0, fat: 21.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Short Ribs (Cooked)", calories: 292, protein: 16, carbs: 0, fat: 24, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Chuck Roast (Raw)", calories: 203, protein: 24.3, carbs: 0, fat: 10.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Chuck Roast (Cooked)", calories: 226, protein: 27, carbs: 0, fat: 12, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Flat Iron Steak (Raw)", calories: 196, protein: 23.4, carbs: 0, fat: 10.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Flat Iron Steak (Cooked)", calories: 218, protein: 26, carbs: 0, fat: 12, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Eye of Round (Raw)", calories: 128, protein: 25.2, carbs: 0, fat: 2.7, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Eye of Round (Cooked)", calories: 143, protein: 28, carbs: 0, fat: 3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Top Round (Raw)", calories: 148, protein: 27, carbs: 0, fat: 3.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Top Round (Cooked)", calories: 165, protein: 30, carbs: 0, fat: 4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Bottom Round (Raw)", calories: 161, protein: 26.1, carbs: 0, fat: 4.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Bottom Round (Cooked)", calories: 179, protein: 29, carbs: 0, fat: 5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Shank (Raw)", calories: 133, protein: 25.2, carbs: 0, fat: 4.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Shank (Cooked)", calories: 148, protein: 28, carbs: 0, fat: 5, grams: 100, mealType: "Protein"),

        FoodItem(name: "Beef Prime Rib (Standing Rib Roast) (Raw)", calories: 315, protein: 19.8, carbs: 0, fat: 25.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Prime Rib (Standing Rib Roast) (Cooked)", calories: 350, protein: 22, carbs: 0, fat: 28, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Back Ribs (Raw)", calories: 270, protein: 18.9, carbs: 0, fat: 21.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Back Ribs (Cooked)", calories: 300, protein: 21, carbs: 0, fat: 24, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Chuck Eye Steak (Raw)", calories: 252, protein: 19.8, carbs: 0, fat: 21.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Chuck Eye Steak (Cooked)", calories: 280, protein: 22, carbs: 0, fat: 24, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Suet (Fatback) (Raw)", calories: 814, protein: 0.9, carbs: 0, fat: 89.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Suet (Fatback) (Cooked)", calories: 905, protein: 1, carbs: 0, fat: 99, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef 7-Bone Roast (Raw)", calories: 225, protein: 20.7, carbs: 0, fat: 16.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef 7-Bone Roast (Cooked)", calories: 250, protein: 23, carbs: 0, fat: 18, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Arm Roast (Raw)", calories: 243, protein: 22.5, carbs: 0, fat: 16.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Arm Roast (Cooked)", calories: 270, protein: 25, carbs: 0, fat: 18, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Blade Steak (Raw)", calories: 238, protein: 21.6, carbs: 0, fat: 16.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Blade Steak (Cooked)", calories: 265, protein: 24, carbs: 0, fat: 18, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Chuck Short Ribs (Raw)", calories: 262, protein: 14.4, carbs: 0, fat: 21.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Chuck Short Ribs (Cooked)", calories: 292, protein: 16, carbs: 0, fat: 24, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef St. Louis-Style Ribs (Raw)", calories: 253, protein: 15.3, carbs: 0, fat: 27, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef St. Louis-Style Ribs (Cooked)", calories: 282, protein: 17, carbs: 0, fat: 30, grams: 100, mealType: "Protein"),

        // Pork Cuts
        FoodItem(name: "Pork Tenderloin (Raw)", calories: 128, protein: 23.4, carbs: 0, fat: 3.15, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Tenderloin (Cooked)", calories: 143, protein: 26, carbs: 0, fat: 3.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Loin Center Cut Chop (Raw)", calories: 180, protein: 25.2, carbs: 0, fat: 8.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Loin Center Cut Chop (Cooked)", calories: 200, protein: 28, carbs: 0, fat: 9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Loin Chop Bone-In (Raw)", calories: 197, protein: 24.3, carbs: 0, fat: 9.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Loin Chop Bone-In (Cooked)", calories: 219, protein: 27, carbs: 0, fat: 11, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Shoulder (Boston Butt) (Raw)", calories: 261, protein: 17.1, carbs: 0, fat: 21.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Shoulder (Boston Butt) (Cooked)", calories: 290, protein: 19, carbs: 0, fat: 24, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Shoulder (Picnic) (Raw)", calories: 198, protein: 14.4, carbs: 0, fat: 15.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Shoulder (Picnic) (Cooked)", calories: 221, protein: 16, carbs: 0, fat: 17, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Spare Ribs (Raw)", calories: 337, protein: 16.2, carbs: 0, fat: 28.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Spare Ribs (Cooked)", calories: 375, protein: 18, carbs: 0, fat: 32, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Baby Back Ribs (Raw)", calories: 254, protein: 17.1, carbs: 0, fat: 18.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Baby Back Ribs (Cooked)", calories: 283, protein: 19, carbs: 0, fat: 21, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Belly (Raw)", calories: 466, protein: 8.1, carbs: 0, fat: 47.7, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Belly (Cooked)", calories: 518, protein: 9, carbs: 0, fat: 53, grams: 100, mealType: "Protein"),
        FoodItem(name: "Bacon (Raw)", calories: 486, protein: 33.3, carbs: 0, fat: 37.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Bacon (Cooked)", calories: 541, protein: 37, carbs: 0, fat: 42, grams: 100, mealType: "Protein"),
        FoodItem(name: "Ham (Cured) (Raw)", calories: 130, protein: 18, carbs: 0, fat: 6.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Ham (Cured) (Cooked)", calories: 145, protein: 20, carbs: 0, fat: 7, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Chop Boneless (Raw)", calories: 207, protein: 23.4, carbs: 0, fat: 10.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Chop Boneless (Cooked)", calories: 230, protein: 26, carbs: 0, fat: 12, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Chop Bone-In (Raw)", calories: 207, protein: 24.3, carbs: 0, fat: 11.7, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Chop Bone-In (Cooked)", calories: 231, protein: 27, carbs: 0, fat: 13, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Shoulder Roast (Raw)", calories: 261, protein: 17.1, carbs: 0, fat: 21.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Shoulder Roast (Cooked)", calories: 290, protein: 19, carbs: 0, fat: 24, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Ham Hock (Raw)", calories: 225, protein: 15.3, carbs: 0, fat: 17.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Ham Hock (Cooked)", calories: 250, protein: 17, carbs: 0, fat: 19, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Jowl (Raw)", calories: 484, protein: 11.7, carbs: 0, fat: 48.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Jowl (Cooked)", calories: 538, protein: 13, carbs: 0, fat: 54, grams: 100, mealType: "Protein"),

        FoodItem(name: "Pork Fatback (Raw)", calories: 811, protein: 0.99, carbs: 0, fat: 89.46, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Fatback (Cooked)", calories: 902, protein: 1.1, carbs: 0, fat: 99.4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Skin (Raw)", calories: 513, protein: 0, carbs: 0, fat: 54, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Skin (Cooked)", calories: 570, protein: 0, carbs: 0, fat: 60, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Cheek (Raw)", calories: 279, protein: 12.6, carbs: 0, fat: 25.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Cheek (Cooked)", calories: 310, protein: 14, carbs: 0, fat: 28, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Ear (Raw)", calories: 337, protein: 63, carbs: 0, fat: 13.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Ear (Cooked)", calories: 375, protein: 70, carbs: 0, fat: 15, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Trotters (Feet) (Raw)", calories: 162, protein: 17.1, carbs: 0, fat: 9.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Trotters (Feet) (Cooked)", calories: 180, protein: 19, carbs: 0, fat: 11, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Sirloin Roast (Raw)", calories: 234, protein: 20.7, carbs: 0, fat: 15.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Sirloin Roast (Cooked)", calories: 260, protein: 23, carbs: 0, fat: 17, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Crown Roast (Raw)", calories: 261, protein: 18.9, carbs: 0, fat: 19.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Crown Roast (Cooked)", calories: 290, protein: 21, carbs: 0, fat: 22, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Country-Style Ribs (Raw)", calories: 331, protein: 18, carbs: 0, fat: 27, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Country-Style Ribs (Cooked)", calories: 368, protein: 20, carbs: 0, fat: 30, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork St. Louis-Style Spare Ribs (Raw)", calories: 337, protein: 16.2, carbs: 0, fat: 28.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork St. Louis-Style Spare Ribs (Cooked)", calories: 375, protein: 18, carbs: 0, fat: 32, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Loin Roast (Raw)", calories: 217, protein: 24.3, carbs: 0, fat: 12.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Loin Roast (Cooked)", calories: 242, protein: 27, carbs: 0, fat: 14, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Leaf Lard (Raw)", calories: 802, protein: 0, carbs: 0, fat: 89.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Leaf Lard (Cooked)", calories: 892, protein: 0, carbs: 0, fat: 99, grams: 100, mealType: "Protein"),

        // Other Poultry & Game
        FoodItem(name: "Guinea Fowl Whole (Raw)", calories: 145, protein: 21.6, carbs: 0, fat: 5.4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Guinea Fowl Whole (Cooked)", calories: 162, protein: 24, carbs: 0, fat: 6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Guinea Fowl Breast (Raw)", calories: 145, protein: 21.6, carbs: 0, fat: 5.4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Guinea Fowl Breast (Cooked)", calories: 162, protein: 24, carbs: 0, fat: 6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Guinea Fowl Leg (Raw)", calories: 144, protein: 20.7, carbs: 0, fat: 4.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Guinea Fowl Leg (Cooked)", calories: 160, protein: 23, carbs: 0, fat: 5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Squab (Pigeon) Whole (Raw)", calories: 110, protein: 21.5, carbs: 0, fat: 2.52, grams: 100, mealType: "Protein"),
        FoodItem(name: "Squab (Pigeon) Whole (Cooked)", calories: 123, protein: 23.9, carbs: 0, fat: 2.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Squab (Pigeon) Breast (Raw)", calories: 108, protein: 21.8, carbs: 0, fat: 2.25, grams: 100, mealType: "Protein"),
        FoodItem(name: "Squab (Pigeon) Breast (Cooked)", calories: 121, protein: 24.2, carbs: 0, fat: 2.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Partridge Whole (Raw)", calories: 120, protein: 22.1, carbs: 0, fat: 2.61, grams: 100, mealType: "Protein"),
        FoodItem(name: "Partridge Whole (Cooked)", calories: 134, protein: 24.6, carbs: 0, fat: 2.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Partridge Breast (Raw)", calories: 119, protein: 22.5, carbs: 0, fat: 2.52, grams: 100, mealType: "Protein"),
        FoodItem(name: "Partridge Breast (Cooked)", calories: 133, protein: 25, carbs: 0, fat: 2.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Partridge Leg (Raw)", calories: 123, protein: 20.43, carbs: 0, fat: 4.68, grams: 100, mealType: "Protein"),
        FoodItem(name: "Partridge Leg (Cooked)", calories: 137, protein: 22.7, carbs: 0, fat: 5.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Wild Turkey Drumstick (Raw)", calories: 154, protein: 25.2, carbs: 0, fat: 5.4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Wild Turkey Drumstick (Cooked)", calories: 172, protein: 28, carbs: 0, fat: 6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Turkey Wing (Raw)", calories: 182, protein: 24.3, carbs: 0, fat: 7.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Turkey Wing (Cooked)", calories: 203, protein: 27, carbs: 0, fat: 8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Turkey Liver (Raw)", calories: 93, protein: 18.36, carbs: 0, fat: 2.79, grams: 100, mealType: "Protein"),
        FoodItem(name: "Turkey Liver (Cooked)", calories: 104, protein: 20.4, carbs: 0, fat: 3.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Turkey Heart (Raw)", calories: 123, protein: 23.49, carbs: 0, fat: 1.98, grams: 100, mealType: "Protein"),
        FoodItem(name: "Turkey Heart (Cooked)", calories: 137, protein: 26.1, carbs: 0, fat: 2.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Duck Heart (Raw)", calories: 166, protein: 27, carbs: 0, fat: 5.4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Duck Heart (Cooked)", calories: 185, protein: 30, carbs: 0, fat: 6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Goose Heart (Raw)", calories: 171, protein: 25.2, carbs: 0, fat: 6.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Goose Heart (Cooked)", calories: 191, protein: 28, carbs: 0, fat: 7, grams: 100, mealType: "Protein"),

        // Organ Meats
        FoodItem(name: "Beef Kidney (Raw)", calories: 92, protein: 15.93, carbs: 0.81, fat: 1.98, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Kidney (Cooked)", calories: 103, protein: 17.7, carbs: 0.9, fat: 2.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Heart (Raw)", calories: 100, protein: 15.93, carbs: 0, fat: 3.96, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Heart (Cooked)", calories: 112, protein: 17.7, carbs: 0, fat: 4.4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Tongue (Raw)", calories: 255, protein: 14.67, carbs: 0, fat: 22.32, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Tongue (Cooked)", calories: 284, protein: 16.3, carbs: 0, fat: 24.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Liver (Raw)", calories: 121, protein: 18.36, carbs: 3.51, fat: 3.24, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Liver (Cooked)", calories: 135, protein: 20.4, carbs: 3.9, fat: 3.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Tripe (Raw)", calories: 76, protein: 10.89, carbs: 0, fat: 3.87, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Tripe (Cooked)", calories: 85, protein: 12.1, carbs: 0, fat: 4.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Sweetbreads (Raw)", calories: 242, protein: 14.58, carbs: 0, fat: 20.34, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Sweetbreads (Cooked)", calories: 269, protein: 16.2, carbs: 0, fat: 22.6, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Brain (Raw)", calories: 128, protein: 8.91, carbs: 0, fat: 9.81, grams: 100, mealType: "Protein"),
        FoodItem(name: "Beef Brain (Cooked)", calories: 143, protein: 9.9, carbs: 0, fat: 10.9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Lamb Kidney (Raw)", calories: 100, protein: 18.18, carbs: 1.35, fat: 2.7, grams: 100, mealType: "Protein"),
        FoodItem(name: "Lamb Kidney (Cooked)", calories: 112, protein: 20.2, carbs: 1.5, fat: 3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Lamb Liver (Raw)", calories: 155, protein: 22.5, carbs: 2.34, fat: 4.86, grams: 100, mealType: "Protein"),
        FoodItem(name: "Lamb Liver (Cooked)", calories: 173, protein: 25, carbs: 2.6, fat: 5.4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Lamb Heart (Raw)", calories: 136, protein: 17.37, carbs: 0, fat: 7.38, grams: 100, mealType: "Protein"),
        FoodItem(name: "Lamb Heart (Cooked)", calories: 152, protein: 19.3, carbs: 0, fat: 8.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Lamb Tripe (Raw)", calories: 76, protein: 10.89, carbs: 0, fat: 3.87, grams: 100, mealType: "Protein"),
        FoodItem(name: "Lamb Tripe (Cooked)", calories: 85, protein: 12.1, carbs: 0, fat: 4.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Kidney (Raw)", calories: 92, protein: 18.45, carbs: 0.81, fat: 2.52, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Kidney (Cooked)", calories: 103, protein: 20.5, carbs: 0.9, fat: 2.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Liver (Raw)", calories: 148, protein: 23.4, carbs: 2.97, fat: 5.67, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Liver (Cooked)", calories: 165, protein: 26, carbs: 3.3, fat: 6.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Heart (Raw)", calories: 100, protein: 14.4, carbs: 0, fat: 4.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Heart (Cooked)", calories: 112, protein: 16, carbs: 0, fat: 5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Tongue (Raw)", calories: 255, protein: 14.85, carbs: 0, fat: 22.32, grams: 100, mealType: "Protein"),
        FoodItem(name: "Pork Tongue (Cooked)", calories: 284, protein: 16.5, carbs: 0, fat: 24.8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Heart (Raw)", calories: 137, protein: 14.4, carbs: 0, fat: 8.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Heart (Cooked)", calories: 153, protein: 16, carbs: 0, fat: 9, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Kidney (Raw)", calories: 93, protein: 15.48, carbs: 0, fat: 3.06, grams: 100, mealType: "Protein"),
        FoodItem(name: "Chicken Kidney (Cooked)", calories: 104, protein: 17.2, carbs: 0, fat: 3.4, grams: 100, mealType: "Protein"),

        // Exotic & Regional Meats
        FoodItem(name: "Ostrich Steak (Raw)", calories: 108, protein: 26.1, carbs: 0, fat: 2.16, grams: 100, mealType: "Protein"),
        FoodItem(name: "Ostrich Steak (Cooked)", calories: 120, protein: 29, carbs: 0, fat: 2.4, grams: 100, mealType: "Protein"),
        FoodItem(name: "Kangaroo Fillet (Raw)", calories: 88, protein: 20.52, carbs: 0, fat: 1.53, grams: 100, mealType: "Protein"),
        FoodItem(name: "Kangaroo Fillet (Cooked)", calories: 98, protein: 22.8, carbs: 0, fat: 1.7, grams: 100, mealType: "Protein"),
        FoodItem(name: "Camel Meat (Raw)", calories: 154, protein: 19.8, carbs: 0, fat: 7.2, grams: 100, mealType: "Protein"),
        FoodItem(name: "Camel Meat (Cooked)", calories: 172, protein: 22, carbs: 0, fat: 8, grams: 100, mealType: "Protein"),
        FoodItem(name: "Yak Meat (Raw)", calories: 131, protein: 18.27, carbs: 0, fat: 4.5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Yak Meat (Cooked)", calories: 146, protein: 20.3, carbs: 0, fat: 5, grams: 100, mealType: "Protein"),
        FoodItem(name: "Alpaca Meat (Raw)", calories: 111, protein: 19.08, carbs: 0, fat: 2.79, grams: 100, mealType: "Protein"),
        FoodItem(name: "Alpaca Meat (Cooked)", calories: 124, protein: 21.2, carbs: 0, fat: 3.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Wild Boar (Raw)", calories: 137, protein: 18.9, carbs: 0, fat: 6.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Wild Boar (Cooked)", calories: 153, protein: 21, carbs: 0, fat: 7, grams: 100, mealType: "Protein"),
        FoodItem(name: "Alligator Meat (Raw)", calories: 128, protein: 17.1, carbs: 0, fat: 5.49, grams: 100, mealType: "Protein"),
        FoodItem(name: "Alligator Meat (Cooked)", calories: 143, protein: 19, carbs: 0, fat: 6.1, grams: 100, mealType: "Protein"),
        FoodItem(name: "Frog Legs (Raw)", calories: 65, protein: 14.4, carbs: 0, fat: 0.27, grams: 100, mealType: "Protein"),
        FoodItem(name: "Frog Legs (Cooked)", calories: 73, protein: 16, carbs: 0, fat: 0.3, grams: 100, mealType: "Protein"),
        FoodItem(name: "Turtle Meat (Raw)", calories: 126, protein: 17.55, carbs: 0, fat: 6.12, grams: 100, mealType: "Protein"),
        FoodItem(name: "Turtle Meat (Cooked)", calories: 141, protein: 19.5, carbs: 0, fat: 6.8, grams: 100, mealType: "Protein"),

    ]
}
